

space : main.o startUp.o show.o update.o
	cc main.o startUp.o show.o update.o -o space

main.o: main.c space.h
	cc -c main.c

startUp.o: startUp.c
	cc -c startUp.c

show.o: show.c
	cc -c show.c

update.o: update.c
	cc -c update.c
